// <auto-generated />
using System;
using ConversorPlanilhaBD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConversorPlanilhaBD.Migrations
{
    [DbContext(typeof(CienciaJovemDb))]
    [Migration("20260821165846_AdicionandoColunaParticipacaoCJ")]
    partial class AdicionandoColunaParticipacaoCJ
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConversorPlanilhaBD.Model.AuxModels.AuxInstituicaoResponsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FuncaoInstituicao")
                        .HasColumnType("text");

                    b.Property<int?>("InstituicaoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstituicaoId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("AuxInstituicoesResponsaveis");
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.Feira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Afiliada")
                        .HasColumnType("text");

                    b.Property<string>("Alcance")
                        .HasColumnType("text");

                    b.Property<string>("AreasConhecimento")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataRealizacao")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<int?>("InstituicaoId")
                        .HasColumnType("integer");

                    b.Property<int?>("InstituicaoOrganizadoraId")
                        .HasColumnType("integer");

                    b.Property<string>("ModalidadeParticipacao")
                        .HasColumnType("text");

                    b.Property<string>("NivelEnsino")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int?>("NumEscolas")
                        .HasColumnType("integer");

                    b.Property<int?>("NumProjetos")
                        .HasColumnType("integer");

                    b.Property<string>("PeriodoElaboracao")
                        .HasColumnType("text");

                    b.Property<string>("PeriodoRealizacao")
                        .HasColumnType("text");

                    b.Property<string>("ProcessoSelecao")
                        .HasColumnType("text");

                    b.Property<string>("ProjetosAvaliados")
                        .HasColumnType("text");

                    b.Property<int?>("ResponsavelContatoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstituicaoId");

                    b.HasIndex("InstituicaoOrganizadoraId");

                    b.HasIndex("ResponsavelContatoId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Feiras");
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.Instituicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adere")
                        .HasColumnType("text");

                    b.Property<string>("ApoioFinanceiro")
                        .HasColumnType("text");

                    b.Property<string>("CNPJ")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("GRE")
                        .HasColumnType("text");

                    b.Property<double?>("IDEB")
                        .HasColumnType("double precision");

                    b.Property<double?>("IDHM")
                        .HasColumnType("double precision");

                    b.Property<string>("Municipio")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("OfertaEnsino")
                        .HasColumnType("text");

                    b.Property<string>("Pais")
                        .HasColumnType("text");

                    b.Property<string>("ParticipacaoCienciaJovem")
                        .HasColumnType("text");

                    b.Property<string>("TipoRede")
                        .HasColumnType("text");

                    b.Property<string>("TipologiaMunicipio")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Instituicoes");
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Genero")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int?>("ProjetoId")
                        .HasColumnType("integer");

                    b.Property<string>("Raca")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Pessoas", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasColumnType("text");

                    b.Property<string>("CategoriaInscricao")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Deficiencia")
                        .HasColumnType("text");

                    b.Property<int?>("FeiraId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("ODS")
                        .HasColumnType("text");

                    b.Property<string>("Objetivo")
                        .HasColumnType("text");

                    b.Property<string>("PalavrasChave")
                        .HasColumnType("text");

                    b.Property<string>("Participacao")
                        .HasColumnType("text");

                    b.Property<int?>("ProfessorId")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<string>("Resumo")
                        .HasColumnType("text");

                    b.Property<string>("Tema")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FeiraId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.ValueObjects.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<int?>("InstituicaoId")
                        .HasColumnType("integer");

                    b.Property<int?>("PessoaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstituicaoId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.ValueObjects.Identidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<string>("OrgaoExpedidor")
                        .HasColumnType("text");

                    b.Property<int?>("PessoaId")
                        .HasColumnType("integer");

                    b.Property<string>("RG")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.ToTable("Identidades");
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.ValueObjects.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("InstituicaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<int?>("PessoaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstituicaoId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.Professor", b =>
                {
                    b.HasBaseType("ConversorPlanilhaBD.Model.Pessoa");

                    b.Property<string>("NumMatricula")
                        .HasColumnType("text");

                    b.ToTable("Professores", (string)null);
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.Responsavel", b =>
                {
                    b.HasBaseType("ConversorPlanilhaBD.Model.Pessoa");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Experiencia")
                        .HasColumnType("text");

                    b.Property<string>("NivelEnsino")
                        .HasColumnType("text");

                    b.Property<string>("Participante")
                        .HasColumnType("text");

                    b.Property<string>("Professor")
                        .HasColumnType("text");

                    b.Property<string>("Recomendacao")
                        .HasColumnType("text");

                    b.ToTable("Responsaveis", (string)null);
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.AuxModels.AuxInstituicaoResponsavel", b =>
                {
                    b.HasOne("ConversorPlanilhaBD.Model.Instituicao", "Instituicao")
                        .WithMany("AuxInstituicaoResponsavel")
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConversorPlanilhaBD.Model.Responsavel", "Responsavel")
                        .WithMany("AuxInstituicaoResponsavel")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Instituicao");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.Feira", b =>
                {
                    b.HasOne("ConversorPlanilhaBD.Model.Instituicao", "Instituicao")
                        .WithMany("Feiras")
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConversorPlanilhaBD.Model.Instituicao", "InstituicaoOrganizadora")
                        .WithMany("FeirasOrganizadas")
                        .HasForeignKey("InstituicaoOrganizadoraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConversorPlanilhaBD.Model.Responsavel", "ResponsavelContato")
                        .WithMany("FeirasContato")
                        .HasForeignKey("ResponsavelContatoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConversorPlanilhaBD.Model.Responsavel", "Responsavel")
                        .WithMany("Feiras")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Instituicao");

                    b.Navigation("InstituicaoOrganizadora");

                    b.Navigation("Responsavel");

                    b.Navigation("ResponsavelContato");
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.Pessoa", b =>
                {
                    b.HasOne("ConversorPlanilhaBD.Model.Projeto", "Projeto")
                        .WithMany("Alunos")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.Projeto", b =>
                {
                    b.HasOne("ConversorPlanilhaBD.Model.Feira", "Feira")
                        .WithMany("Projetos")
                        .HasForeignKey("FeiraId");

                    b.HasOne("ConversorPlanilhaBD.Model.Professor", "Professor")
                        .WithMany("Projetos")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConversorPlanilhaBD.Model.Responsavel", "Responsavel")
                        .WithMany("Projetos")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Feira");

                    b.Navigation("Professor");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.ValueObjects.Email", b =>
                {
                    b.HasOne("ConversorPlanilhaBD.Model.Instituicao", "Instituicao")
                        .WithMany("Email")
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConversorPlanilhaBD.Model.Pessoa", "Pessoa")
                        .WithMany("Email")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Instituicao");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.ValueObjects.Identidade", b =>
                {
                    b.HasOne("ConversorPlanilhaBD.Model.Pessoa", "Pessoa")
                        .WithOne("Identidade")
                        .HasForeignKey("ConversorPlanilhaBD.Model.ValueObjects.Identidade", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.ValueObjects.Telefone", b =>
                {
                    b.HasOne("ConversorPlanilhaBD.Model.Instituicao", "Instituicao")
                        .WithMany("Telefone")
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConversorPlanilhaBD.Model.Pessoa", "Pessoa")
                        .WithMany("Telefone")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Instituicao");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.Professor", b =>
                {
                    b.HasOne("ConversorPlanilhaBD.Model.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("ConversorPlanilhaBD.Model.Professor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.Responsavel", b =>
                {
                    b.HasOne("ConversorPlanilhaBD.Model.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("ConversorPlanilhaBD.Model.Responsavel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.Feira", b =>
                {
                    b.Navigation("Projetos");
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.Instituicao", b =>
                {
                    b.Navigation("AuxInstituicaoResponsavel");

                    b.Navigation("Email");

                    b.Navigation("Feiras");

                    b.Navigation("FeirasOrganizadas");

                    b.Navigation("Telefone");
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.Pessoa", b =>
                {
                    b.Navigation("Email");

                    b.Navigation("Identidade");

                    b.Navigation("Telefone");
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.Projeto", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.Professor", b =>
                {
                    b.Navigation("Projetos");
                });

            modelBuilder.Entity("ConversorPlanilhaBD.Model.Responsavel", b =>
                {
                    b.Navigation("AuxInstituicaoResponsavel");

                    b.Navigation("Feiras");

                    b.Navigation("FeirasContato");

                    b.Navigation("Projetos");
                });
#pragma warning restore 612, 618
        }
    }
}
